export const FRIEND_GET_SUCCESS = "FRIEND_GET_SUCCESS";
export const MESSAGE_GET_SUCCESS = "MESSAGE_GET_SUCCESS";
export const MESSAGE_SEND_SUCCESS = "MESSAGE_SEND_SUCCESS";
export const GROUPS_GET_SUCCESS = "GROUPS_GET_SUCCESS";
export const GET_MEMBER_SUCCESS = "GET_MEMBER_SUCCESS";
